# @package _global_
machine_name: desktop

checkpoints_dir: /home/nicola/Desktop/anyprune/checkpoints
cache_dir: /home/nicola/Desktop/anyprune/cache
outputs_dir: /home/nicola/Desktop/anyprune/outputs

dl3dv_root_dir: /home/nicola/Desktop/Anysplat-improved/datasets/dl3dv
dl3dv_images_subdir: images_8

# Loose ceiling on the amount of gaussians the GPU can hold in memory at 
# training time
device_max_gaussians: 500_000

# How many views to rasterize at once.
device_max_views_per_render: 2
